version: "3.8"

services:
  netbanking:
    image: arunshaik2001/netbanking:docker
    container_name: netbanking
    ports:
      - "4000:4000"
      - "5173:5173"
    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: on-failure
    networks:
      - common

networks:
  common:
    external:
      name: common
