version: "3.8"

services:
  netbanking:
    container_name: netbanking-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5173:5173"
    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: on-failure
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - common



networks:
  common:
      driver: bridge
      name: common