version: "3.8"

services:
  netbanking:
    container_name: netbanking-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
      - "5173:5173"
    volumes:
      - ./:/app/
      - /app/node_modules/
    restart: on-failure
    environment:
      - DATABASE_URL=postgresql://postgres:rised@postgres:5432/mydb?schema=public
    networks:
      - common
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_client
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always
    networks:
      - common

networks:
  common:
    external:
      name: common

volumes:
  redis: